### ISSUE TITLE
Review Issue

### ISSUE THREAD

**Issue by dgsierra** [dgsierra/capstone-ruby#48]
Hi! 👋

Link to de repo: [Link](https://github.com/dgonzalesi/capstone-ruby)

People in the team: **4**

List of members:
@robinbenitezmora - Team Meber#1
@mullenlucas  - Team member#2
@dgonzalesi  - Team meber#3
@Ol-create  - Team member#4

 🫱🏼‍🫲🏽

**Comment by tufoinnkuo10** [comment]
Hi @Team

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ Descriptive  message


Required Changes ♻️
- [x] please kindly ensure you don't mix up the team member numbers as they are used to check the different task. wrong team member numbers/image are used in different instance in your board. please fix that. eg
![Screenshot (606)_LI](https://user-images.githubusercontent.com/65298048/203170879-b3ef4539-cc8f-4ef5-a5b2-b896559ad89e.jpg)
- [x] kindly remove unused cards or cards not assigned to anyone from the board.
![Screenshot (607)_LI](https://user-images.githubusercontent.com/65298048/203171159-7160205a-061c-42fc-afb3-f081762143ab.jpg)
- [x] please if a task is not a group task it should be assigned to one person so as to avoid confusion. don't you think it will be confusing when you add a card belongs to a particular member then you assign it to two members. please check that.
![Screenshot (608)_LI](https://user-images.githubusercontent.com/65298048/203171641-f6fdcc2c-b588-4737-b819-e47f024d4c61.jpg)
- [x] please ensure that all cards have points located to them
![Screenshot (609)_LI](https://user-images.githubusercontent.com/65298048/203172073-0ed5badf-89e3-449f-9470-322affd9dcab.jpg)
- [x] please ensure all cards have their owners team member number. this helps to see how the work is been distributed. since all cards don't have points and team member number, it is difficult to see if the work was fairly distributed. the next reviewer will check that.


Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good setup 👏🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
